### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by onikienko** [Test458000/Rosped#1]
Hello there,

Код виглядає як робочий. Це добре. (В роботі не перевіряв, тільки подивився `script.js`.) 

Окрім того що код має бути робочим, він має бути написаний максимально оптимально (жерти мінімум русурсів), має легко розширюватись (в разі змін в специфікації) і легко підримуватись.

Тут є багато критичних помилок. Спочатку виправимо і оптимізуємо код який є. Потім треба буде переписати все "правильно" (для того будуть наступні issue)

Тож оптимізація інсуючого коду:

Всі операції з DOM потребують багато ресурсів. Зазвичай задача всіх front-end розробників - мінімізувати операції з DOM тому що це суттєво півищує швидкість виконання коду. 

В твоєму коді ти для кожного збігу слова отримуєш весь вміст DOM, замінюєш слово якщо знайшлось і перемальовєш всю сторінку!!! Якщо тут буде пару сотень слів (або тисяч, або сотень тисяч), то розширення тупо "повість" браузер. 

Тож треба:

**Прочитати DOM один раз. Зробити всі заміни. Після того оновити DOM один раз**

До того, ж уяви собі якщо в тебе 100 000 слів на заміну. Ти сто тисяч разів будеш писати руками в коді: `a.replace(/вихіднеСлово/g, 'словоДляЗаміни')`  ?  Для таких випадків (операції що повторюються) треба використовувати цикли.  
Я б зробив десь так:

````JavaScript
const dictUK = {
    'Росія': 'Педерація',
    'Росії': 'Педерації',
   // і тп
};

````

Такий самий словиник для рос мови. І потім вже обходив би їх в `for in` циклі.

Або уяви собі що дані для заміни ти отримуєш з сервера (зазавичай так і буде) і не знаєш їх одразу.
Тож також зможеш обійти їх в томуж циклі....

---------------------------------------------

Зміни зробити на новому branch з іменем `dev`. Commit message в якому ти все це виправляєш має містити посилання на це issue. Типу `Resolved #1`. 

Додавати `.crx` не треба. Тільки вихідний код.

**Comment by onikienko** [comment]
Про всяк випадок. Цей `dev` бранч має бути "відрощений" (branch out) від останнього комміту на `master`

**Comment by Test458000** [comment]
Спасибо!
Сделал. Все  работает.
Единственная проблема - при активном расширении не работают POST-запросы. Тут не знаю где копать....
