### ISSUE TITLE
Use Dictionary from the server

### ISSUE THREAD

**Issue by onikienko** [Test458000/Rosped#2]
Використовувати словник з сервера - http://sbox.pp.ua/ext/dict.json  
Для отримання використовувати [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)   (Взагалі при розробці розширень для Chrome ми майже завди можемо використовувати майже всі новітні фішки)

Зверни увагу що додана Англійська мова для заміни. І можливо будуть додані ще.

**Comment by onikienko** [comment]
Я подумав, що можливо ти збираєшся завантажувати цей словник з сервера на кожній сторінці де треба робити заміну.  

Зазвичай робиться інакше. Словник завантажується один раз (як правило все набагато заплутаніше - треба вантажити через якийсь інтервал, напрклад щоденно, обо існує окремий url де зберігається номер версії словника і те перевіряєш його). Для спрощення пропустимо все це.

Тож можна завантажити словник один раз (наприклад, при встановленні) і запам'ятати його. Також кожного разу при старті розширення, можна перевіряти, чи є збережений словник, якщо нема - спробувати завантажити з сервера.  Десь так, якщо спрощено....

І всі це роботи з завантаження, перевірки, зберігання як раз то і можна виконутвати на цих Event Pages які ти пригадав в #4

**Comment by Test458000** [comment]
Я собирался загрузить словарь с сервера, обработать его и запомнить в константу. Потом перегружать его при запуске расширения. 
Если доступа к словарю нет - ловить ошибку через промисы, наверное, и использовать ранее загруженный.

**Comment by onikienko** [comment]
Ти маєш запам'ятати його таким чином, щоб він зберігався між сесіями. Щоб не треба було завантажувати кожен раз при старті розширення.

А при старті перевіряти, чи збережений він чи ні. Якщо ні - завантажити та збереги. Потім, за потреби можна буде додати інші правила, як от завантажувати раз на 24 години, перевіряти версію і тп.

Можна використовувати [Chrome Storage](https://developer.chrome.com/extensions/storage) для збереження.

**Comment by Test458000** [comment]
Ага, спасибо.
Так намного проще, а то я уже в такие дебри залез....

**Comment by Test458000** [comment]
Бьюсь над заданием уже который день по способу 1 - ничего не выходит.  Сегодня попробовал 2-ой способ - тоже ничего.
Миша, на всякий случай хочу спросить: а это задание вообще выполнимо голым JavaScript?

Способ 1. Попробовал вывести объект с помощью fetch в основной код, и в нем уже обрабатывать объект. Проблема - fetch не возвращает объект, объект могу использовать только внутри запроса.

 Способ 2. Попробовал все это сделать внутри  fetch,  тогда станицы выдают ошибку:
"'https://javascript.ru/forum/misc/30691-sozdat-peremennuyu-v-cikle.html' was loaded over HTTPS, but requested an insecure resource 'http://sbox.pp.ua/ext/dict.json'. This request has been blocked; the content must be served over HTTPS."

**Comment by onikienko** [comment]
> а это задание вообще выполнимо голым JavaScript?

так це типова задача

можеш зробити commit з "Способ 1"? я подивлюсь

**Comment by onikienko** [comment]
Способ 2

В самому тілі помилки все описано.  Ти намагаєшся завантажити незахищені дані (http) із захищеної сторінки (https). Це заборонено на рівні протоколів. Небезпечно.  

Роби це в розширенні.

**Comment by Test458000** [comment]
По способу 2 понятно, я прочитал. 
Хорошо, верну способ 1 назад - и отправлю.
Спасибо.

**Comment by Test458000** [comment]
Я залил. Проблема с областями видимости - я и напрямую объект пробовал получить, и через функцию как сейчас, и переприсваивал объект и так и сяк - никак. 
Внутри фетча словарь обрабатываю, а снаружи получаю только undefined. В интернетах как-то не смог найти ответ.

Если и правда простая задача, то я еще помучаюсь.

**Comment by onikienko** [comment]
Подивився.  

Проблема не в scope ("областями видимости"). Тут декілька інших проблем. Це ОК, типові помилки починаючих js розробників.

Багато речей в javascript працює асінхронно.   Тож як насправді працює твоя `function  get_dict(lng_res)`   

Ти об'являєш змінну `let temp;`. Вона отримає значення undefined. (всі змінні без призначенного значення мають є undefined.)   
Ти викликаєш fetch.  `fetch` повертає `Promise` (перекладається як Обіцянка). fetch обіцяє, що КОЛИ він БУДЕ мати данні з сервера, функції задані в .then(function) будуть виконані. Він не блокує виконання всього коду що лежить далі.   
Ти запустив fetch і інтерпретатор побіг виконувати  наступний код не чекаючи поки fetch закінчить.  
Тож твій `alert (temp);` в строчці 40, буде завжди видавати undefined. Тому що на цей момент fetch ще не закінчив.   А твій `return  lng_res;` також буде завжди повертати undefined (до того ж з ним справді проблеми з scope). І твій const dict_all = get_dict(); буже завжди undefined.

Коли fetch закінчить, ти побачиш `alert (temp);` із строчки 40. Але вже буде занадто піздно тому що весь код вже виконаний :)

Тож js потребує інштого підходу ніж знайомий тобі з php (ти ніби з php? бо в js зазвичай використовують верблюжий регістр (camelCase) для назви всього, типу getDict() а не get_dict())

Найпростіший варіант - замість того щоб щось повертати з твоєї `function  get_dict(lng_res)`  ти можешь зробити `function getAndSaveDict()`. Тоб-то в останньому then одразу збереги словник в chrome.storage.local   І робити це ти маєш в eventPage а не в content script. Контент скріпт має тільки працювати з сторінкою. Контент скріпт буде чиплятися браузером до кожної сторінки яку юзер відкриває. Не треба там нічого вантажити. Він має бути маленький. Щоб отримати словник він буде читати chrome.storage.local

Десь так. 
![code_2018-11-21_21-42-39](https://user-images.githubusercontent.com/3234928/48864831-7b2b0000-edd6-11e8-8d67-f697e3b23d0d.png)

**Comment by onikienko** [comment]
Коменти в коді зробив англійською за звичкою. Сподіваюсть і так буде зрозуміло

**Comment by onikienko** [comment]
Якщо є якись питання про асинхронність - давай. Бо це важлива тема

**Comment by onikienko** [comment]
Доречи, chrome.storage.local також асинхронний, але він повертає не Promise, а викликає так звану callback функцію.  
Певно ти ще не знайомий з цією концепцією. Почитай щось. Я не знаю де гарно написано російською. Може це https://ru.hexlet.io/blog/posts/javascript-what-the-heck-is-a-callback
Має бути багато інфи, бе весь js на callback працює

**Comment by Test458000** [comment]
Спасибо, Миша!
Про асинхронность я понял - по последовательности алертов было видно, только думал, что есть секретные методы или это решается только при помощи фреймворков (про chrome.storage.local я даже упоминаний не встречал).

Про переменные - мне так понятнее, иначе имена методов, функций и переменных для меня сливаются в кашу - буду перестраиваться. По php только видосики смотрел.

**Comment by onikienko** [comment]
`chrome.storage.local` це частина Chrome Extensions API (використовується тільки в розширеннях, це НЕ частина javascript) https://developer.chrome.com/extensions/storage   
Тут можна зберігати дані і вони будуть доступні наступної сесії (після того як юзер закриє і відкриє chrome знову)

> Про переменные - мне так понятнее

Можеш писати як тобі зручно. Це не проблема. В js прийнято camelCase. 

Ця фішка з асинхронністю js може здаватися важкою на початку. Тому що потребує трошки іншого підходу. Але з довсвідом ти звикнеш. Головне з самого початку намагатися грамотно з цим працювати.  
Інкше код перетвориться на  так званий callback hell (пекло з callbackів). Також це називають spaghetti code. Коли купа колбеків один в одному і без пів-літри не розберешся. Я дивлюсь на свій дуже старий код і хочеться плакати :)

**Comment by Test458000** [comment]
Если код рабочий, то это супер! 
Миша, мне от моих потуг хочется плакать:) Я думал, что я умнее минимум в 10 раз. 
Загрузил, что удалось сделать. Все комментарии и пожелания я учел.

Что в коде не так:
1. Мне кажется, что словарь не сохраняется, а все время заново загружается, по алертам видно (алерты сейчас закомментированы). Или это мне только кажется?
2. Страницы разрушаются, но это, я так понял, из-за "div": "division". Так и есть?

И по-честному: для передачи из бекпейджа в контент я слямзил чужой код, немного модифицировав. Свой код написать с нуля не получилось.

**Comment by Test458000** [comment]
Страницы уже не разрушаются - описание что и как в Fix logic #3, я его еще продолжаю делать.

Словарь все время заново перезаписывается, хотя по коду не должен. Или это Хром так работает?

**Comment by onikienko** [comment]
Привіт. Я був у відпустці. Сьогодні гляну на код трохи згодом.

> для передачи из бекпейджа в контент я слямзил чужой код, немного модифицировав.   

взяти готовий/чужий код це добре (якщо ліцензії не порушує).  але chrom.storage доступний з content script. я підозрюю що ти передавава через sendMessage. гляну пізніше.

> Миша, мне от моих потуг хочется плакать:)

Я так підозрюю що проблеми з тією ж асинхронністю. Це нормально. Досвід потрібен. Все прийде з практикою.

**Comment by Test458000** [comment]
Привет, Миша! 
С днем рождения тебя!
Крепкого здоровья тебе и прибыльных проектов!

Да, через sendMessage отправлял. Так борол асинхронность....
Третье задание я делаю потихоньку.  Надо код пилить и скиллы подтягивать:)

**Comment by onikienko** [comment]
Дякую за привітання :)

#3 не треба зараз. Ти там трохи не те робиш. Зараз по цьому issue спробую пояснити

**Comment by onikienko** [comment]
Подивився код. Тільки `background.js`. Треба все переробити. Давай на якийсь час забудемо про #3. Треба довести до тями завантажженя і зберігання словника з сервера.

Проблеми наступні:
1.  непраильне використання chrome.storage
2.  неправильна робота з callback (ти намагаєшся писати синхронний код, але це не працює, тому що все асинхронне, тобто не виконується одне за одним)

Тож 1.   

Дивимось документацію. https://developer.chrome.com/apps/storage   

Приклади використання з документації:

````JavaScript
        chrome.storage.local.set({key: value}, function() {
          console.log('Value is set to ' + value);
        });
      
        chrome.storage.local.get(['key'], function(result) {
          console.log('Value currently is ' + result.key);
        });
````
 В твоєму коді, ти зберигаєш в storage в функції `setDict ()`:

`chrome.storage.local.set(dictLast, function () {});`

dictLast в тебе буде якимось чином перевірений і відфільтрований словник з сервера (пропустимо поки обговорення цього `checkDictWords` ). 
Тобто:

dictLast = {
  ru: {},
  ua: {},
  en: {}
}

з парами `слово: словоНаЯкеМіняти` всередені кожної мови. І ти це записуєш в chrome.storage.local. Чудово.   
Виходячи з фрагменту коду з документації вище, в тебе в chrome.storage.local буде збережено 3 ключи (змінні) - ru, ua, uk. Те що нам і треба. (Я планував записати весь словник під одним ключєм, але так також буде працювати. Не проблема. Хай буде 3 - один ключ одна мова)

 Далі дивимось функцію `getDict()`. Вона буду завжди повертати `undefined` (`невизначенно`). Ти читаєш значення з storage не правильно. В першому параметрі методу chrome.storage.local.get ти маєш вказати ЯКІ ключи (змінні) із сховища ти хочеш прочитати. Як в документації:

````JavaScript   
        chrome.storage.local.get(['key'], function(result) {
          console.log('Value currently is ' + result.key);
        });
````

Оцей ['key'] - це масив з іменами ключив. В нашому випадку ти маєш зробити так:

````JavaScript   
        chrome.storage.local.get(['ru', 'ua', 'en'], function(result) {
          console.log('ru ' + result.ru); // виведе в консоль наш словник для рос мови
          console.log('en ' + result.en); // виведе в консоль наш словник для English
          // теж саме для української можна зробити
        });
````

Але замість ['ru', 'ua', 'en'] ти передаєш dictRes якій буде або undefined або цілий словник записаний десь там вище в коді. Ти нічого не читаєш з storage. Цей storage (сховище) зберігає пару ключ: значення.

Якщо мені треба зберігти значення `5`  в змінну `a` я буду робити так:

 ````JavaScript
        chrome.storage.local.set({a: 5}, function() {
          console.log('Value is set to ' + value);
        });
````

А щоб потім прочитати:

````JavaScript    
        chrome.storage.local.get(['a'], function(result) {
          console.log('a is ' + result.a); // виведе:  "a is 5"
        });
````

-----------------

Про "неправильна робота з callback" напишу трошки згодом. Треба переключитись на роботу.

**Comment by onikienko** [comment]
Тож 2 (callbacks і асинхронність):

Щось читаючи з сервера, або chrom.storage (є купа інших випадків) ми маємо асинхронний код. Випадок з fetch ми вже розглядали, давай зараз на прикладі chrome.storage.

Скажімо ти хочеш прочитати значення `a` з chrome.storage, яке я записав в кінці попереднього комента. Нехай весь код залежить від цього `a`.  (Наприклад, тобі треба запустити alert, `a`  разів)

Ти б зробив певно десь так:

````JavaScript
let a;

function getA() {
	chrome.storage.local.get(['a'], function (res) {
		a= res.a;			
	});
	return a;	
};
````

Функція getA() буде повертати undefined. код не буде чекати поки chrome.storage.local.get поверне
результат. Після запуску метода chrome.storage.local.get одразу виконається наступний фрагмент коду (return a;) На момент виконання це буде undefined. Колись згодом, коли chrome.storage.local.get отримає результат, буде запущений callback функція, яка в нашому випадку є: `function (res) {a= res.a;}` Але твоє getA() вже повернуло значення.   

У випадках асинхронного коду, треба запускати код, який ти хочеш виконати (функцію) замість повернення результату.  Тож замість робит return в таких випадках, ти запускаєш функцію яка має бути виконана. 

Тож код має виглядати так:

````JavaScript
// скрипт виводить щось в консоль `a` разів

function writeAtimes(a) {
	for (let i = 0; i < a; i++) {
		console.log(i);
	}
}

function getA() {
    chrome.storage.local.get(['a'], function (res) {
        // замість повертати щось, або записувати в глобальну змінну,
	// я викликю код, який має бути виконаний, коли ми отримали значення `a`
        writeAtimes(res.a);
    });
}

getA();
````

Дай мені значити, чи щось розвиднілось для тебе.   
Я думаю, може я напишу робочий код, і ти спробуєш розібратися. Але непогано, самостійно спробувати.

**Comment by onikienko** [comment]
Більш правильний варіант останнього прикладу буде через callback:

````JavaScript
// скрипт виводить щось в консоль `a` разів

function writeAtimes(a) {
	for (let i = 0; i < a; i++) {
		console.log(i);
	}
}

function getA(callback) {
    chrome.storage.local.get(['a'], function (res) {
        // замість повертати щось, або записувати в глобальну змінну,
	// я викликаю callback з `a` як параметр
        callback(res.a);
    });
}

getA(function(a) {
   writeAtimes(a);
});
````

Чи зрозуміло тобі, як це працює?

**Comment by Test458000** [comment]
Спасибо, Миша! 
По асинхронности мне понятно. Ну, я так и старался делать в .then - я сначала присваивал новое значение в функции, а потом его передавал. 
У меня есть большая проблема, я так понял - это правильное чтение документации. Слова мы читаем одни и те же, а понимаем по-разному.  Я уже в 20 раз больше морщу лоб - и снова беда.
Я хочу сам доделать код.

**Comment by onikienko** [comment]
Ок.  

Май на увазі, що ти можеш читати chrome.storage.local.get напряму з content script (файл script.js в твоєму випадку) Не треба ця комунікація через onMessage/sendMessage (але непогона, що ти вже ознайомився з цим API)

Ось в доках про це написано:
http://sbox.pp.ua/up/chrome_2018-11-28_16-11-55.png

**Comment by Test458000** [comment]
Миша, спасибо тебе огромное за такие развернутые ответы!
И ты мне можешь писать намного меньше, чтобы времени столько не тратить.
Например, в п.1 достаточно было указать мне, что я с ключами провтыкал - chrome.storage записывается и вызывается по ключам. Я поколупаю и разберусь.  Твое же время сейчас намного ценнее моего, а я себе поколупаю доки, еще что-то изучу....

По п.2 тоже понятно - все вытекает из п.1.

Я понимаю, но как та собака сказать ничего не может, так и мне написать что-то вменяемое пока сложно:)

**Comment by onikienko** [comment]
Ок.

Мені з кода здалось, що ти зовсім загубився з асинхронністю. Тож вирішив трохи глибше пояснити. Це найголовніша частина. І може здаватись найважчою, бо людський спосіб мислення синхронний :)

Також рекомендую тобі встановити WebStorm або Visual Studio Code. 

WebStorm з коробки тобі буде купу твоїх помилок підсвічувати: http://sbox.pp.ua/up/webstorm64_2018-11-28_16-37-44.png

Visual Studio Code безкоштовний, але його також можна налаштувати і затарити плагінами. 

Це все тобі життя дуже спростить.

**Comment by Test458000** [comment]
Миша, я переделал. Но словарь все равно проходит через бекграунд, я не понимаю как его брать сохраненным...

**Comment by Test458000** [comment]
Кстати, я getDict () запускал в контенте - все равно проходит через бекграунд... Может, я словарь не так проверяю?

P.S. По программах - у меня Notepad++. Говорят, что для новичков лучше с него начинать. Может, врут...
Я уже и WebStorm, и Visual Studio Code скачал пару недель назад - все не установлю никак, времени жалко, хочется побольше поучиться.

**Comment by onikienko** [comment]
> Миша, я переделал. Но словарь все равно проходит через бекграунд, я не понимаю как его брать сохраненным...

**script.js**
````JavaScript
    chrome.storage.local.get(['dictionary'], (res) => {
        if (res.dictionary) {
          // словник є, можна зупускати весь інший код в роботу
          replaceWords(res.dictionary);
          // тільки треба щоб твоя replaceWords  приймала "dict" як параметр, а не використовувала десь там на початку оголошену змінну
        }
    });
````

Це все. Весь інший код в **script.js** зайвий. 

Але **background.js** все одно не робочий. 

Десь так має бути:
![code_2018-11-28_18-47-28](https://user-images.githubusercontent.com/3234928/49167477-1c1d3c00-f33e-11e8-9ecd-8d61c59084da.png)

Все інше, наскільки я розумію, зайве.

**Comment by Test458000** [comment]
Я делал так, чтобы словарь обрабатывался в контенте, а задача бекграунда только словарь выдавать для последующей замены слов.
Хорошо, спрячу все в бекграунд.

**Comment by onikienko** [comment]
> По программах - у меня Notepad++. Говорят, что для новичков лучше с него начинать. Может, врут...

Брешуть. Інфа сотка :) 

Маючи WebStom (якщо він в тебе вже  є) будеш мати купу підказок по коду і попередження для можливих помилок. Нема сенсу зубрити як конкретно писати якійсь метод. Достатньо знати що він є.   
До того ж воно само відкладеться, якщо 100 разів в коді буде.    
Наприклад, в тебе в 'checkDictWords()' оголошено декілька глобальних змінних (нема let, const чи var - тож такє стає автоматично глобальним). Notepad++ тобі не підкаже, а WebStorm вкаже на це. І після певної кількості таких зауважень ти вже сам будеш не забувати..... І ось тоді ти вже зможеш писати в Notepad чи де завгодно........

> Я делал так, чтобы словарь обрабатывался в контенте, а задача бекграунда только словарь выдавать для последующей замены слов.

Я честно кажучи не зрозумів що ти маєш на увазі під "словарь обрабатывался в контенте". У нас є словник. Ми його вантажимо (якщо ще не збережено) з сервера і зберігаємо в сховище. Контет скріпт читає сховище.

**Comment by Test458000** [comment]
Спасибо! Установил WebStom - попробую...

Про бекграунд - это я объясняюсь: я думал, что цель так делать - это чтобы https страницы не выдавали ошибки на наш скрипт, а весь код писать в script.js, из бекграунда подтягивать только словарь.
Наверное, из-за этого и ошибки с проверкой словаря.
Осознал, что нужно все делать в бекграунде, а в script.js отображать минимум.
С учетом этого и начинаю переделывать. Может, и ошибка проверки уйдет.

А переменные я специально делал глобальными, это сознательный ход...

**Comment by onikienko** [comment]
Ок. 

Бєкраунд, якщо треба, на старті качає словник з сервера, і зберігає в сховище.  
Контен скріпт - читає словник із сховища. Якщо в сховищі словник є - виконує якусь роботу (заміну слів i тп), якщо словника нема - не робить нічого.

З приводу  "ошибки с проверкой словаря" - нічого перевіряти не треба. Зберігай як є. Читай мій останній коммент з #3 

> А переменные я специально делал глобальными, это сознательный ход...

Так не можна. Треба шукати інші шляхи для розв'язання задач без використання глобальних змінних. 

Твою функцію можна переписати так (без глобальних змінних):

```JavaScript
function checkDictWords(dict) {
    const checkedDict = {};
    for (let langName in dict) {
        checkedDict[langName] = {};
    	for (let word in dict[langName]) {
    		if (config.tagList.indexOf(word) === -1) {
    		    // слова нема в tagList, записуємо в checkedDict
                    checkedDict[langName][word] = dict[langName][word];
    		}
	}
    }
    return checkedDict;
}
````
Але як я вже казав, ця функія не потрабна. Читай #3

**Comment by Test458000** [comment]
Раз ты все рассказал, то я все быстро переделал. Код получился совсем маленький и простой.
По проверке словаря - я проверял, сохранился ли словарь в script.js в переменную или нет. Теперь нет переменной, так что и проверять нечего:)
Глобальные переменные постараюсь больше не использовать.

По функции - такую конструкцию я еще не пробовал. Интересная.
Завтра буду бороться с #3
