### ISSUE TITLE
Fix logic #3

### ISSUE THREAD

**Issue by Test458000** [Test458000/Rosped#5]
Зараз код оптимізований (окрім того що словник можна обходити один раз і правити body і title в одному циклі)

Але тут є одна велика проблема. Коли ти почнеш використовувати словник з сервера (#2) твоє розширення буде тупо ламати всі сторінки які юзер відкриває. Тому що всі HTML теги `<div>`, `</div>` стануть `<division>`, `</division>`.

**Comment by Test458000** [comment]
@Test458000 Прокоментуй, будь ласка, як ти плануєш розв'язати цю проблему

**Comment by Test458000** [comment]
Случайно закрыл Fix logic #3  - создал новый.

**Comment by onikienko** [comment]
ok. без проблем. 

 доречи, закриті issue можна відкривати знову.

**Comment by Test458000** [comment]
Ага, увидел наконец-то где это. Так что это закрою, чтобы не нарушать структуру.
